go vet fixes
mauricext4fs/cig-exchange-homepage-backend pull request #2
Opened 2018-12-27 12:03 UTC by alexgblr

2018-12-27 13:16 UTC, alexgblr commented
https://www.pivotaltracker.com/story/show/162833172

2018-12-27 17:28 UTC, mauricext4fs requested changes
I don't even see the reason for this pull request at all.

2018-12-27 17:28 UTC, mauricext4fs commented on controllers/authControllers.go
> +		fmt.Printf("Error adding template: %v\n", err)
?? Why not Println?

2018-12-27 18:00 UTC, alexgblr commented on controllers/authControllers.go
> +		fmt.Printf("Error adding template: %v\n", err)
try running "make test". 
go vet will issue those errors.
Println is not intended to have a format specifier, printF does.

https://golang.org/pkg/fmt/#Println
Println formats **using the default formats for its operands** and writes to standard output. Spaces are always added between operands and a newline is appended. It returns the number of bytes written and any write error encountered.

https://golang.org/pkg/fmt/#Printf
Printf formats according to a **format specifier** and writes to standard output. It returns the number of bytes written and any write error encountered

There are 3 ways to do logging w/o adding redundant '\n'
1. use log package. log.Printf inserts a newline automatically
2. use fmt.Println("Error adding template: " + err.Error()) - but this quickly gets out of control when you insert something in the middle
3. use fmt.Sprintf as an argument to fmt.Printl - also ugly

2018-12-27 19:03 UTC, alexgblr commented
https://www.pivotaltracker.com/story/show/162862349

2018-12-27 19:43 UTC, mauricext4fs commented
ok... you win again :)

Sent from my iPad

> On 28 Dec 2018, at 02:03, alexgblr <notifications@github.com> wrote:
> 
> https://www.pivotaltracker.com/story/show/162862349
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-12-27 20:16 UTC, alexgblr commented
please merge. I created separate viv for that one.

2018-12-28 09:42 UTC, mauricext4fs approved these changes

2018-12-28 09:42 UTC, merged